"""empty message

Revision ID: 1aa3c2ba348a
Revises: fccb551aefaa
Create Date: 2018-05-29 14:56:53.283291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa3c2ba348a'
down_revision = 'fccb551aefaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('russian', sa.String(length=64), nullable=False),
    sa.Column('english', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translems_english'), 'translems', ['english'], unique=False)
    op.create_index(op.f('ix_translems_russian'), 'translems', ['russian'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translems_russian'), table_name='translems')
    op.drop_index(op.f('ix_translems_english'), table_name='translems')
    op.drop_table('translems')
    op.drop_table('topic')
    # ### end Alembic commands ###
