"""empty message

Revision ID: 283241ace598
Revises: 75b9f1de32f3
Create Date: 2018-05-29 18:39:02.601027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283241ace598'
down_revision = '75b9f1de32f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('translems_topic_id_fkey', 'translems', type_='foreignkey')
    op.create_foreign_key(None, 'translems', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translems', type_='foreignkey')
    op.create_foreign_key('translems_topic_id_fkey', 'translems', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###
