"""empty message

Revision ID: 75b9f1de32f3
Revises: 1aa3c2ba348a
Create Date: 2018-05-29 15:29:05.248202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b9f1de32f3'
down_revision = '1aa3c2ba348a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_my_constrain', 'translems', ['russian', 'english', 'topic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_my_constrain', 'translems', type_='unique')
    # ### end Alembic commands ###
