"""empty message

Revision ID: a3b156175b37
Revises: f4807928e479
Create Date: 2018-08-06 13:06:41.298773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b156175b37'
down_revision = 'f4807928e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_teacher')
    # ### end Alembic commands ###
