"""empty message

Revision ID: f4807928e479
Revises: 5c3edc112f2d
Create Date: 2018-05-29 20:26:06.148994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4807928e479'
down_revision = '5c3edc112f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'topic', ['topic_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='unique')
    # ### end Alembic commands ###
